Repository Walkover-Web-Solution/chatbot-ui, pull requests merged in 2025-08, with the labels that each got.

#122 MAIN = Fix logic for subThread selection
  store/appInfo/appInfoSlice.ts
Labels: bug Fix, Prod deployement

#124 Main = solve the Iconflickerig issue by asyn-await
  public/chatbot-dev.js
  public/chatbot-local.js
  public/chatbot.js
Labels: bug Fix, Prod deployement

#126 multiple image genration main
  components/Interface-Chatbot/Messages/AssistantMessage.tsx
Labels: Prod deployement

#128 testing sync with test 8 aug
  components/Chatbot/hooks/useHelloEffects.ts
  components/Chatbot/hooks/useHelloIntegration.ts
  components/Interface-Chatbot/ChatbotHeader.tsx
  components/Interface-Chatbot/ChatbotTextField.tsx
  components/Interface-Chatbot/Messages/AssistantMessage.tsx
  components/Interface-Chatbot/Messages/HumanOrBotMessage.tsx
  components/Interface-Chatbot/Messages/ImageWithFallback.tsx
  components/Interface-Chatbot/Messages/MessageTime.tsx
  components/Interface-Chatbot/Messages/UserMessage.tsx
  hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
  public/chat-widget-dev.js
  public/chat-widget-local.js
  public/chat-widget-prodtesing.js
  public/chat-widget-style.css
  public/chat-widget.js
  public/urlMonitor.js
Labels: dev deployment
